Repository preludeorg/community, pull requests merged in 2021-05, with the labels that each got.

#111 Adding a reverse shell TTP for the new shell handlers
  command-and-control/f2440a34-d2d8-41b2-b8d4-5eb468ac506c.yml
Labels: size/S

#113 Add LocalGroup Enum TTP Variant
  discovery/d7add940-1137-4975-b7d5-cab9a107a6c6.yml
Labels: size/L

#114 Add Open Share Enumeration using netapi32 NetShareEnum
  discovery/756b6e3d-aab7-4e9e-8bf0-0ccdcea2697f.yml
Labels: size/L

#115 Add "Discover System Geolocalization" T1614 TTP
  discovery/4d2c97ed-5464-4a27-9cc4-f76237526aea.yml
Labels: size/S

#119 Adding a Travis pipeline to handle TTP update actions
  .travis.yml
  requirements.txt
  ttp_handler.py
Labels: size/M

#116 Adds Powershell variant to Delete Volume Shadow Copies
  impact/280f0330-e862-44b9-9a57-0459ef118c8d.yml
Labels: size/XS

#117 Adds Retrieve Domain Restricted Groups GPOs Procedure
  discovery/7de00454-d90c-4b72-97b1-ee1bb37f31e7.yml
Labels: size/L
