Repository preludeorg/community, pull requests merged in 2021-03, with the labels that each got.

#69 Adds the Capability of Enumerate Local Groups
  discovery/d7add940-1137-4975-b7d5-cab9a107a6c6.yml
Labels: size/M

#79 TTP's for Defense Evasion and Credential Access
  credential-access/067bf93d-75d5-4acf-8058-59c0f8104ed4.yml
  defense-evasion/8feb27ce-63db-472f-b8e9-038134e9d79a.yml
  defense-evasion/e4209652-91f4-4c7b-8b5d-db246bb08764.yml
Labels: size/M

#80 Added Defense Evasion TTP - Disable PowerShell event logging
  defense-evasion/a03cd1a6-c32d-437c-84bf-574174ef9db0.yml
Labels: size/S

#82 AMSI Protection Providers Enumeration TTP
  discovery/221bc8bd-077f-41cb-bc14-f415442e7082.yml
Labels: size/M

#88 Adds Powershell variant using Get-GPOReport | T1201
  discovery/e82f39e2-56f8-4f19-8376-b007f9ac5f8a.yml
Labels: size/XS

#89 Add variant to Domain User Creation TTP | T1136.002
  persistence/dc6a04c2-535d-4593-b7e4-ff226a449c67.yml
Labels: size/XS

#90 Remove unnecessary lines in t1201
  discovery/e82f39e2-56f8-4f19-8376-b007f9ac5f8a.yml
Labels: size/S

#81 create ttp
  discovery/00010203-0405-0607-0809-0a0b0c0d0e0f.yml
  discovery/16fd2706-8baf-433b-82eb-8c7fada847da.yml
  discovery/9fe853c0-2cd7-49dc-88b4-ccbc25029dd7.yml
Labels: size/M

#91 TTPs for shadowhashdata and enable root (macOS) & lsass dump via createdump
  credential-access/3d1a91c9-e1a8-4d40-aaf3-05594e7be41a.yml
  credential-access/6044fb78-5d7b-43cc-9592-dcba3c4537f1.yml
  privilege-escalation/62933e77-9c3c-49be-9152-6990a654abf9.yml
Labels: size/M

#94 Uploading remaining fixes
  credential-access/3d1a91c9-e1a8-4d40-aaf3-05594e7be41a.yml
  discovery/be674970-449b-4eb6-95c3-251ee90bea69.yml
Labels: size/XS

#95 Fixing Pneuma download link
  command-and-control/5f9001dc-e179-451f-bbd1-9fb4466d7057.yml
Labels: size/XS

#96 Adds Delete Volume Shadow Copies variant using WMIC
  impact/280f0330-e862-44b9-9a57-0459ef118c8d.yml
Labels: size/XS

#97 Add reg query variant
  discovery/2488245e-bcbd-405d-920e-2de27db882b3.yml
Labels: size/XS

#100 Adding variant from PR #92
  discovery/b480cb71-713a-42e7-ac18-cb408cb58a40.yml
Labels: size/XS

#98 Adds a Powershell Implementation for querying the Registry for Passwords
  credential-access/3aad5312-d48b-4206-9de4-39866c12e60f.yml
Labels: size/M

#101 Add Service Enumeration Variants
  discovery/c6607391-d02c-44b5-9b13-d3492ca58599.yml
Labels: size/S
