Repository preludeorg/community, pull requests merged in 2021-06, with the labels that each got.

#121 putting made file on desktop
  impact/47d08617-5ce1-424a-8cc5-c9c978ce6bf9.yml
Labels: size/XS

#123 Removing powershell variations that defender catches
  discovery/756b6e3d-aab7-4e9e-8bf0-0ccdcea2697f.yml
  discovery/d7add940-1137-4975-b7d5-cab9a107a6c6.yml
Labels: size/L

#124 updating leave note ttp to work on global/node
  impact/47d08617-5ce1-424a-8cc5-c9c978ce6bf9.yml
Labels: size/XS

#126 Adds "Retrive AWS Region" TTP
  discovery/3fe792b0-66eb-40fc-aea1-bd6de5a97083.yml
Labels: size/S

#127 Adds "AWS Instance Metadata Discovery" TTP
  discovery/4d5de7b1-4c9f-4a46-ae0b-1622bd6931e0.yml
Labels: size/S

#129 Adds "Discover Kerberos Cached Tickets" TTP
  discovery/5d18deaa-f32b-48f8-9ef6-71e3eb4d90c7.yml
Labels: size/S

#130 Adds Alternative methods of Disabling Windows Defender Features
  defense-evasion/b007f6e8-4a87-4440-8888-29ceab047d9b.yml
Labels: size/S

#132 fixes release dates
  defense-evasion/b007f6e8-4a87-4440-8888-29ceab047d9b.yml
  discovery/3fe792b0-66eb-40fc-aea1-bd6de5a97083.yml
  discovery/5d18deaa-f32b-48f8-9ef6-71e3eb4d90c7.yml
Labels: size/S

#125 Add "Find Kerberoastable Accounts" TTP
  discovery/27b922c1-76ca-41c7-926f-1c36cabec122.yml
Labels: size/M

#128 Add "Request RC4 encrypted Kerberos TGS Service Ticket" TTP
  credential-access/fd8f1dfe-9ab2-4a60-9f75-810472d9bb22.yml
Labels: size/S

#138 Removing stale TTP and upgrade for Pro users
  credential-access/5c90420e-7972-4125-833b-16c89d5c303f.yml
Labels: size/M

#136 Adds Powershell Logging Disable Procedures
  defense-evasion/11c8c5a7-81d2-43af-8b87-42cba6259790.yml
  defense-evasion/7cb61bef-4ce8-498c-9a16-b37187a0c195.yml
  defense-evasion/f53ef70f-4768-440d-bc6a-ff9120d7c37b.yml
Labels: size/M

#131 Adds Windows Defender exclusion Procedures
  defense-evasion/458e7ec1-6177-4bee-a89d-a6ffe9b1a043.yml
  defense-evasion/b8242780-1177-4dbf-a3d3-4c8d7c13d3c1.yml
Labels: size/M
